117 product related layouts
Voog/design-boilerplate pull request #118
Opened 2021-03-08 11:11 UTC by robertpihelgas

Added Product and Product list layouts.
Close #117 

Some guides for testing:

- [ ] Check if bgpicker, image drop area and page/article image saving works properly in the following layouts:

    - [ ]     Product list
    - [ ]     Product

- [ ] Check if Product list layout works properly everywhere.
- [ ] Check if Product layout works properly everywhere.
- [ ] Check if Blog & news layout didn't broke down.
- [ ] Check if Product list layout works up to second level in menu.
- [ ] Check if Product list works for root item (first page).
- [ ] Check if Product works for root item (first page).
- [ ] Check if main menu in desktop didn't broke down.
- [ ] Check if main menu in mobile didn't broke down.
- [ ] Do a small check for all other layouts to see if something got broken.

2021-04-07 08:12 UTC, siimha requested changes
Mõned asjad jäid silma ja osad vajaksid ka Nuukis muudatusi.

2021-04-07 08:12 UTC, siimha commented on components/javascripts.tpl
> +      {%- if page.layout_title == product_list_layout or page.layout_title == product_layout -%}
Siin mallis kasutakse drop areat ja pildi alt seadistud vaid `product_list_layout` ja `product_layout ` mallides ehk sellega seotud kood initsialiseerida vaid antud mallides (`if page.layout_title == product_list_layout or page.layout_title == product_layout`). `product_list_layout ` oleks vist õigem 'drag_picture_here' tõlge (Nuukis peaks ka muutma).

2021-04-07 08:12 UTC, siimha commented on sources/javascripts/concat/global/main.js
> +  var bgPickerImageSizesContains = function (sizes, url) {
Bg Pickeriga seotud koodi võiks liigutada `editmode.js`i

2021-04-07 08:12 UTC, siimha commented on sources/javascripts/concat/global/main.js
> +  var handleDocument = function() {
Seda kasutatakse ka vaid muutmise vaates.

2021-04-07 08:12 UTC, siimha commented on sources/javascripts/concat/global/main.js
> +  var toggleImageSettingsPopover = function () {
Seda kasutatakse ka vaid muutmise vaates.

2021-04-07 10:55 UTC, robertpih commented on sources/components/custom-styles/template-cs-style-rules.scss
> +  font-family: var(--main-font-family);
Ei. :)

2021-04-13 07:11 UTC, siimha requested changes
Hakkab looma!

2021-05-05 10:45 UTC, siimha requested changes

2021-05-05 10:45 UTC, siimha commented on sources/javascripts/concat/global/main.js
> +  // Initiates the table horisontal scroll function when window is resized.
Alates sellest reast, kuni `init` funktsioonini liigutada lõõpu `// Enables the usage of the initiations outside this file.` rea ette.

2021-05-05 10:45 UTC, siimha commented on sources/stylesheets/utils/_utils.scss
> +  position: absolute !important;
Siin pole `!important` tingimust vaja.

2021-05-05 10:48 UTC, siimha commented
[See](https://github.com/Voog/design-boilerplate/pull/118#discussion_r612178500) on ka veel sisse viimata.

2021-05-06 08:58 UTC, tanelj requested changes

2021-05-06 08:58 UTC, tanelj commented on components/product-item.tpl
> +{% unless productImage != blank %}
Topelt eitus ei ole hea. Parem on `if productImage == blank`

2021-05-06 08:58 UTC, tanelj commented on components/product-item.tpl
> +        _targetWidth: '700',
Kas siin on mingi põhjusega `_targetWidth=700?` Mujal koodis on 600 ja 1280.

Praegusel hetkel pakub Voog piltide järgmis [standard suuruseid](https://www.voog.com/developers/markup/basics/smarter-media) `600`, `1280`, `2048`. Seega väärtus 700 valib suuruse 1280.

2021-05-06 08:58 UTC, tanelj commented on components/product-list-block-item.tpl
> +          {{ _entityData.title }}
Väärtus on pm kasutaja sisestatav ja võib sisaldada `>` jne märke. Tuleks turvata (`escape_once`).

2021-05-06 08:58 UTC, tanelj commented on manifest.json
> +      "layout_name": "page_default",
Layout name tohib olla "page_default" ainult ühel lehel (tüüpiliselt common page) siin peaks olema `product_list`

2021-05-06 08:58 UTC, tanelj commented on manifest.json
> +      "title": "Product"
Product lehe layout_name peab olema "product".

2021-05-10 14:02 UTC, siimha requested changes
Paar asja jäi veel silma ja lisa siis tootelehele _breadcrumbs_.

2021-05-12 08:02 UTC, tanelj commented on sources/javascripts/concat/global/main.js
> +  var toggleImageSettingsPopover = function () {
See muudatus vist veel sisse viimata?

2021-05-12 08:04 UTC, tanelj commented on sources/javascripts/concat/global/main.js
> +    handleProductPageContent: handleProductPageContent
Kas seda `handleProductPageContent` kasutatakse kusagil?

2021-05-13 09:43 UTC, robertpih commented on sources/javascripts/concat/global/main.js
> +    handleProductPageContent: handleProductPageContent
Ei. Mida copyd, seda pasted. Tegu Nuukispetsiifilise funktsiooniga. Viskasin välja.

2021-05-17 10:25 UTC, siimha requested changes

2021-05-17 10:25 UTC, siimha commented on components/menu-breadcrumbs.tpl
> +<ul class="menu menu-horizontal menu-public menu-breadcrumbs">
Jetkel väga palju iteratioone saanud (`menu-breadcrumbs-items-loop`, `menu-breadcrumbs`, `menu-breadcrumbs-buttons-loop`) ja selle asemel võiks kasutada `sd_breadcrumbs ` [datat](https://www.voog.com/developers/markup/tags/sd-breadcrumbs), siis ei pea nii palju itereerima. Aktiivse lehe leivapuru element ei peaks link olema (sama bugi paljudes mallides):
```
{%- capture breadcrumbsScript -%}
  {%- sd_breadcrumbs -%}
{%- endcapture -%}
{%- assign breadcrumbsString = breadcrumbsScript | replace: '<script type="application/ld+json">', '' | replace: "</script>", '' | replace: site.url, '' | replace: '@', '' -%}
{%- assign breadcrumbsObj = breadcrumbsString | json_parse -%}

<nav class="menu-sub menu-breadcrumbs content-formatted">
  <ul class="menu">
    {%- for listItem in breadcrumbsObj.itemListElement %}
      {% unless forloop.index == 1 %}
        {%- assign pageUrl = page.url | remove_first: "/" -%}

        {%- if pageUrl == listItem.item.id -%}
          {%- assign breadcrumbTag = 'div' -%}
          {%- assign isCurrentPage = true -%}
        {%- else -%}
          {%- assign breadcrumbTag = 'a' -%}
          {%- assign isCurrentPage = false -%}
        {%- endif -%}

        <li class="menu-item">
          <{{breadcrumbTag}} class="menu-link {% if forloop.index > 2 %} with_arrow {% endif %} {% if pageUrl == listItem.item.id %} active{% endif %}" {% if pageUrl != listItem.item.id %}href="/{{listItem.item.id}}"{% endif %}>
            {{listItem.item.name}}
          </{{breadcrumbTag}}>
        </li>
      {% endunless -%}
    {% endfor -%}
  </ul>
</nav>
```

2021-05-20 08:45 UTC, siimha requested changes
Mõned tähelepanekud :)

2021-05-21 07:51 UTC, siimha requested changes
[See](https://github.com/Voog/design-boilerplate/pull/118/files#r630795896) on ka veel sisse viimata, aga muidu pm valmis

2021-05-21 07:51 UTC, siimha commented on sources/stylesheets/_menus.scss
> +    @media screen and (min-width: $desktop-1 + 1) {
Ma arvan, et siin piisab ühest fondi suurusest.

2021-05-21 11:16 UTC, tanelj requested changes

2021-05-21 11:16 UTC, tanelj commented on layouts/product_list.tpl
> +        <main class="content" role="main" data-search-indexing-allowed="true">
Toodete list ise ei peaks olema indekseeritud. `data-search-indexing-allowed="true"` peaks olema `content-body` divi küljes.

2021-05-21 11:16 UTC, tanelj commented on sources/javascripts/concat/global/main.js
> +
Üleliigsed tühikud.

2021-05-21 11:16 UTC, tanelj commented on sources/stylesheets/_variables.scss
> +
Üleliigsed tühikud.

2021-05-21 11:16 UTC, tanelj commented on sources/stylesheets/components/_image-drop-area.scss
> +
Üleliigsed tühikud.

2021-05-21 11:16 UTC, tanelj commented on components/menu-level-2.tpl
> +        {% if editmode %}
`menu-level-2` vajab täiendamist:
* Kui `parent` on tootelisti tüüpi, siis ei tohiks kuvada müra vähendamiseks:
  * Teisi tooteliste
  * Tooteid
* Add page peaks ilmselt olema "tavaline" "add subpage", kuna listingu vaatesse on nagunii vaja toote lisamise nuppu (sügavamatesse tootekategooriatesse toodete lisamise lahendamiseks).

2021-05-21 11:16 UTC, tanelj commented on layouts/product_list.tpl
> +        {% include "menu-level-2" %}
Selleks, et saaks ka sügavamate kategooriate korral lisada tooteid, on vaja listingu vaatesse ka eraldi "add product" nuppu.

2021-05-25 09:39 UTC, siimha requested changes

2021-05-25 11:01 UTC, tanelj approved these changes

2021-05-25 11:18 UTC, siimha approved these changes
Tubli ja tänud, et aitasid ka Nuuki koodi selle tööga parandada.

2021-05-25 11:29 UTC, merged