Add auto-generated product layout
Voog/design-boilerplate pull request #123
Opened 2022-01-31 09:37 UTC by pxska

Closes #122.

2022-02-03 14:36 UTC, tanelj requested changes
Very good, but some minor comments!

Please also add
* [x] Webkit image fix https://github.com/Voog/design-santiago/commit/7d6f73c1424e946cf108c3f5bb3475488ac2bca9#diff-d543c7ef54a2ad318b0bd7a534b83515eab150ff158798967ce5d6953b8783ad

2022-02-03 14:36 UTC, tanelj commented on components/buy-button.tpl
> +  data-settings="{&quot;title&quot;:&quot;{{ "add_to_cart" | lc | escape_once }}&quot;,&quot;button_style&quot;:&quot;with_price&quot;}"
The price is allready on the page.

```suggestion
  data-settings="{&quot;title&quot;:&quot;{{ "add_to_cart" | lc | escape_once }}&quot;}"
```

2022-02-03 14:36 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +{% capture bottom_content_html %}
Let's strip white spaces here and below (until body)

```suggestion
{%- capture bottom_content_html %}
```

2022-02-03 14:36 UTC, tanelj commented on sources/javascripts/concat/global/main.js
> +      var buyBtnContent = $('.js-buy-btn-content');
Mayby its more readable to add class like `js-product-content-right` to product right column wrapper and use it here (like in Santiago https://github.com/Voog/design-santiago/pull/230/files#diff-96d8063d0f25fce87494d9213aa996cf6bf3e4288934f4e77634d45ee6abfe82R1075)

2022-02-03 18:24 UTC, PeeterPaal requested changes
Seems nice! Just a few nitpicks:

The margins seem too large. This makes the content area under product image quite narrow (compared to regular `Product` layout).

2022-02-03 18:24 UTC, PeeterPaal commented on layouts/auto_generated_product.tpl
> +                    {{ product.price_min_with_tax | money_with_currency: product.currency -}}
Missing indent

2022-02-07 12:11 UTC, tanelj approved these changes
Nice!

2022-02-07 12:13 UTC, PeeterPaal approved these changes
Looks good!

2022-02-10 10:47 UTC, tanelj requested changes
Works, but some technical remarks.

2022-02-10 10:47 UTC, tanelj commented on components/template-variables.tpl
> +  {% comment %}Detects viewing mode.{% endcomment %}
Separate `view_mode` is not needed. We have all ready `html.editmode` class.

2022-02-10 10:47 UTC, tanelj commented on layouts/auto_generated_product.tpl
> +    template && template.handleProductPageContent();
Let's use only `window.site`.

2022-02-10 10:47 UTC, tanelj commented on layouts/product.tpl
> +                  <div class="content-item-title content-area" data-search-indexing-allowed="true">
`data-search-indexing-allowed="true"` is all ready presented in prev line.

```suggestion
                  <div class="content-item-title content-area">
```

2022-02-10 10:47 UTC, tanelj commented on sources/javascripts/concat/global/main.js
> +  window.template = $.extend(window.template || {}, {
We don't need separate `window.template`. Please use use `window.site`.

2022-02-10 12:09 UTC, PeeterPaal approved these changes
Looks good!

2022-02-10 20:09 UTC, tanelj approved these changes

2022-02-10 20:09 UTC, merged