Fix popover and breadcrumbs menu
Voog/design-boilerplate pull request #125
Opened 2022-02-11 10:51 UTC by PeeterPaal

Closes #124

2022-02-14 13:17 UTC, pxska approved these changes
One small comment, otherwise looks good!

2022-02-14 13:17 UTC, pxska commented on components/menu-breadcrumbs-sd.tpl
>      {%- assign pageUrl = page.url | remove_first: "/" -%}
`pageUrl` isn't necessary in this context anymore.

2022-02-16 15:46 UTC, tanelj requested changes
Nice, but one unused variable.

2022-02-16 15:46 UTC, tanelj commented on components/menu-breadcrumbs-sd.tpl
> +  {%- assign rootShown = true -%}
Unused variable
```suggestion
  {%- assign rootShown = true -%}
```

2022-02-17 08:29 UTC, tanelj approved these changes

2022-02-17 08:40 UTC, pxska approved these changes

2022-02-17 11:57 UTC, merged